[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opp-py"
version = "0.1.0"
description = "ODIN Provenance Passport — Python instrumentation + CLI"
requires-python = ">=3.10"
dependencies = [
  "httpx>=0.27.0",
  "cryptography>=43.0.1",
  "typer>=0.12.4",
]

[project.scripts]
opp = "opp.cli:app"
