name: opp-ci

on:
  push:
  pull_request:

jobs:
  py-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install opp_py
        run: |
          python -m pip install --upgrade pip
          pip install -e packages/opp_py
          pip install -r services/exporter_api/requirements.txt
      - name: Run tests
        run: |
          python -m pytest -q
